package calcException;

public class ArithmeticException extends Exception{
    ArithmeticException(){
        super("The exception raised in arithmetic operation.\n");
    }
}
